### ISSUE TITLE
Clear input after submit and prevent resubmission by refreshing

### ISSUE THREAD

**Issue by taiqn** [ashutoshkrris/Flask-URL-Shortener#2]
Hi there,

Great project, happy to download and deploy your code.

It would be nice if you could add some code to clear the input form (or at least the 'url') after user click on SHORTEN or Submit button,  to prevent user from refreshing the page to spam the database.

Thanks

**Comment by ashutoshkrris** [comment]
Thanks @taiqn 
For your usage, you can remove the value attribute from Line 12 and Line 18 in this file: https://github.com/ashutoshkrris/Flask-URL-Shortener/blob/main/core/templates/index.html

**Comment by taiqn** [comment]
Thanks @ashutoshkrris
