### ISSUE TITLE
Prevent resubmission by refreshing after clicking submit button

### ISSUE THREAD

**Issue by taiqn** [ashutoshkrris/Flask-URL-Shortener#3]
Hi @ashutoshkrris, I got lot of spam rows in the database because of resubmission after refreshing. If you help me to prevent this, will be happy to send you some $SHIB.

Thanks
Tai

**Comment by ashutoshkrris** [comment]
Sure @taiqn 
Will check and let you know.

**Comment by ashutoshkrris** [comment]
Hi @taiqn 
Please find the updated code in this branch: https://github.com/ashutoshkrris/Flask-URL-Shortener/tree/issue3
Changes made: https://github.com/ashutoshkrris/Flask-URL-Shortener/commit/5160ab91d394f9f0eca38f73bb5bbc8792cc4bc9

**Comment by taiqn** [comment]
Nice one, @ashutoshkrris thanks 🎉🎉🎉
Now please let me know your Binance ID / username  or BEP20 $SHIB address.

**Comment by ashutoshkrris** [comment]
It's okay, @taiqn 
You don't need to send anything, it's open source.
Happy to help!

**Comment by taiqn** [comment]
For your precious time I'm willing to send, so @ashutoshkrris please become member of the #SHIBARMY (if not yet).
